Repository ynput/ayon-shotgrid, pull requests merged in 2024-12, with the labels that each got.

#76 `server` Simple support to sync users from SG over to Ayon
  frontend/dist/index.html
  frontend/dist/shotgrid-addon.js
Labels: community, type: feature

#132 Ignoring Task entities with no step key
  server/settings/main.py
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/ayon_shotgrid_hub/match_ayon_hierarchy_in_shotgrid.py
  services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_shotgrid.py
  services/shotgrid_common/utils.py
Labels: type: enhancement, sponsored

#113 AY-7217_Add support to sync task assignees and statuses for all entities
  server/__init__.py
  services/leecher/leecher/listener.py
  services/processor/processor/processor.py
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/ayon_shotgrid_hub/match_ayon_hierarchy_in_shotgrid.py
  services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_shotgrid.py
  services/shotgrid_common/constants.py
  services/shotgrid_common/utils.py
  services/transmitter/transmitter/transmitter.py
Labels: type: enhancement, community, sponsored, bump minor

#153 Added missing default_task_type
  services/shotgrid_common/ayon_shotgrid_hub/match_ayon_hierarchy_in_shotgrid.py
Labels: type: bug

#154 Note/comment synchronization
  server/settings/main.py
  service_tools/requirements.txt
  services/processor/processor/processor.py
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_shotgrid.py
  services/shotgrid_common/constants.py
  services/shotgrid_common/utils.py
  services/transmitter/transmitter/transmitter.py
Labels: type: feature, sponsored
