Repository ynput/ayon-shotgrid, pull requests merged in 2024-10, with the labels that each got.

#114 Ignore events by default unless it's a supported event by non-api user
  services/leecher/leecher/listener.py
Labels: community

#136 Chore: Add ruff linting
  .github/workflows/pr_linting.yml
  ruff.toml
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
Labels: type: maintenance

#135 Chore: Use 'AYON' in logs and docstrings
  README.md
  client/ayon_shotgrid/plugins/publish/integrate_shotgrid_version.py
  client/ayon_shotgrid/plugins/publish/validate_shotgrid_user.py
  client/ayon_shotgrid/tray/sg_login_dialog.py
  client/ayon_shotgrid/tray/shotgrid_tray.py
  server/__init__.py
  services/Makefile
  services/leecher/README.md
  services/leecher/leecher/listener.py
  services/leecher/pyproject.toml
  services/manage.ps1
  services/processor/processor/processor.py
  services/processor/pyproject.toml
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/ayon_shotgrid_hub/match_ayon_hierarchy_in_shotgrid.py
  services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_shotgrid.py
  services/shotgrid_common/utils.py
  services/transmitter/pyproject.toml
  services/transmitter/transmitter/transmitter.py
Labels: type: maintenance

#134 Chore: Update versions during create package
  create_package.py
Labels: type: maintenance

#139 Chore: Fix usage of missing function
  client/ayon_shotgrid/tray/sg_login_dialog.py
Labels: type: bug
