Repository ynput/ayon-shotgrid, pull requests merged in 2024-11, with the labels that each got.

#111 Small fixes
  client/ayon_shotgrid/plugins/publish/integrate_shotgrid_version.py
  services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
Labels: community

#146 Chore: Add upload to Ynput Cloud action
  .github/workflows/upload_to_ynput_cloud.yml
Labels: type: maintenance

#122 Shotgrid: reviving archived assets is broken
  services/leecher/leecher/listener.py
  services/processor/processor/processor.py
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_shotgrid.py
  services/shotgrid_common/utils.py
Labels: type: bug, sponsored

#147 Remodeling settings for Re-parenting of SG entity types for AYON hierarchy
  server/settings/main.py
  services/shotgrid_common/utils.py
Labels: type: enhancement, sponsored

#145 Sync: Prepare for ayon api change
  services/shotgrid_common/utils.py
Labels: type: enhancement

#129 Sequence and shot folder grouping
  server/settings/main.py
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/ayon_shotgrid_hub/match_ayon_hierarchy_in_shotgrid.py
  services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_ayon.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_shotgrid.py
  services/shotgrid_common/constants.py
  services/shotgrid_common/utils.py
Labels: type: enhancement, sponsored
