Repository ynput/ayon-shotgrid, pull requests merged in 2025-04, with the labels that each got.

#191 Fix copy paste typo
  services/transmitter/transmitter/transmitter.py
Labels: type: maintenance

#185 Add settings validators and processor service preflight checks.
  client/ayon_shotgrid/addon.py
  client/ayon_shotgrid/lib/__init__.py
  client/ayon_shotgrid/lib/credentials.py
  client/ayon_shotgrid/tray/sg_login_dialog.py
  client/ayon_shotgrid/tray/shotgrid_tray.py
  server/settings/main.py
  services/processor/processor/processor.py
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/utils.py
  services/shotgrid_common/validate.py
Labels: type: enhancement

#197 AY-7631 Fix Flow notes from Version not parented properly to AYON.
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_shotgrid.py
  services/shotgrid_common/constants.py
  services/shotgrid_common/utils.py
Labels: type: bug, sponsored

#200 AY-7632 Ensure date attributes are synced between Flow and AYON
  server/settings/main.py
  services/shotgrid_common/utils.py
Labels: type: bug, sponsored

#203 Fix user synchronization from frontend Shotgrid tab.
  frontend/dist/shotgrid-addon.js
Labels: type: bug

#201 Front-End improvements for ayon-shotgrid.
  frontend/dist/index.html
  frontend/dist/shotgrid-addon.css
  frontend/dist/shotgrid-addon.js
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
Labels: type: enhancement, sponsored

#204 AY-7598 Fix sync task statuses
  services/shotgrid_common/ayon_shotgrid_hub/match_ayon_hierarchy_in_shotgrid.py
  services/shotgrid_common/ayon_shotgrid_hub/update_from_ayon.py
  services/shotgrid_common/utils.py
Labels: type: bug, sponsored
