Repository ynput/ayon-shotgrid, pull requests merged in 2025-05, with the labels that each got.

#211 Report missing attributes sync for Version.
  services/shotgrid_common/utils.py
Labels: type: bug

#202 Bi-Directional attachments sync on notes/comments
  services/shotgrid_common/ayon_shotgrid_hub/__init__.py
  services/shotgrid_common/utils.py
Labels: type: enhancement

#205 Ignore events from non-locally-existent projects when pulling from Flow (optimization)
  services/leecher/leecher/listener.py
Labels: type: enhancement

#217 Sync version without task
  services/shotgrid_common/utils.py
Labels: type: bug, sponsored

#213 Fix typo
  services/transmitter/transmitter/transmitter.py
Labels: type: bug

#215 Fixed missing argument
  services/shotgrid_common/ayon_shotgrid_hub/update_from_shotgrid.py
Labels: type: bug, sponsored

#216 Fixed accessing scope from None
  services/shotgrid_common/utils.py
Labels: type: bug

#220 Fix Synchronize Users for existing user login.
  frontend/dist/shotgrid-addon.js
Labels: type: bug

#223 Ignore SG events coming from ourselves.
  services/leecher/leecher/listener.py
Labels: type: bug

#227 Rework datetime conversion and exception catch.
  services/shotgrid_common/utils.py
Labels: type: bug

#225 Support all Flow project tracking settings.
  services/shotgrid_common/utils.py
Labels: type: bug
